language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
branches:
  only:
    - master
install:
  - npm install closure closure-library closurecompiler commander xmldom xpath
  - export TRAVIS=true
  - sed -i s/\'-d32\'//g /home/travis/build/zorkow/speech-rule-engine/node_modules/closure-library/closure/bin/build/jscompiler.py
